### ISSUE TITLE
Arm?

### ISSUE THREAD

**Issue by samuk** [jakoch/jupyter-devbox#5]
I tried running this on a ARM device but got

exec /usr/bin/bash: exec format error

Which I think is an architecture issue? Do you have any interest in supporting Arm?

**Comment by jakoch** [comment]
Yes, this is an architecture issue.  It would require to use an "per-architecture" build of Debian, so that it fits the underlying machine. One could clone the existing Dockerfile and base it on an ARM based debian, e.g.
- https://hub.docker.com/r/arm32v7/debian/ = ` FROM arm32v7/debian:latest`
- https://hub.docker.com/r/arm64v8/debian/ = ` FROM arm64v8/debian:latest`

I'll give it a try...

**Comment by jakoch** [comment]
Dev Notes:

- Tensorflow
 - https://www.wheelodex.org/projects/tensorflow/
  - https://www.piwheels.org/project/tensorflow/
  - https://www.tensorflow.org/lite/guide/build_arm 
  - build with elinux_armhf on arm32v7?
  - build tflite?
- OpenCV
  - switch to opencv-headless
- prefer-binary
- switch packages to apt, if building takes to long

**Comment by samuk** [comment]
I ended up playing with [this container](https://github.com/silaskalmbach/Docker_RaspberryPi4_JupyterLab) which does run on ARM, but is a little old.

[Some notes](https://github.com/Agroecology-Lab/Mycodo?tab=readme-ov-file#ai-container) of the stuff I was playing around with.

**Comment by jakoch** [comment]
- The `arm32v7` container is build and working. I'm not sure how long this will take on GHA.
I had to disable compiling tensorflow and opencv-headless. 
opencv is now fetched via apt. I'm still searching for a tensorflow wheel.

![image](https://github.com/jakoch/jupyter-devbox/assets/85608/db4acabf-e212-4f10-8174-1d0ac09f401d)


- While browsing the links you provided, i noticed an alternative container init for RaspberryPi4?
Is it needed? https://github.com/silaskalmbach/Docker_RaspberryPi4_JupyterLab/blob/master/Dockerfile#L47-L51

**Comment by samuk** [comment]
Nic, thanks.

Not sure, about the init I can give your version a go later and see if it works.

I've found the apt opencv is so old it's largely incompatible with any new tooling. The Python3 version seems to work for the things I've been playing with

**Comment by jakoch** [comment]
- i've dropped python3-opencv and released v1.3.0
- haven't released the arm build, yet, because of dependency issues
- had to revert the piwheels setup, because it  doesn't resolve any dependencies
  - the wheels are installed, but it will fail on the example notebooks, due to missing deps
  - when installing matplotlib, deps missing: pillow pyparsing cycler
  - when installing pandas, deps missing: peewee pytz appdirs frozendict multitasking 
- thanks for pointing out vision-process-webui. this looks very promising, but unfortunately it won't work, because of the missing tensorflow dependency - https://github.com/isLinXu/vision-process-webui/blob/main/requirements.txt#L7
   - its also a project, which is better git cloned into the box, instead of provided by default

**Comment by samuk** [comment]
Ah the joys of Debian dependencies. I note [this one](https://github.com/silaskalmbach/Docker_RaspberryPi4_JupyterLab/blob/master/Dockerfile) is Ubuntu based, and whilst being two years old seemed to have fewer dependency problems.

I'm a Debian fan, my laptop runs it, but I wonder if for CV stuff an Ubuntu base makes more sense?

**Comment by samuk** [comment]
Thanks, still can't get it going unfortunately.

Stuck ghcr.io/jakoch/jupyter-devbox:sha-09b8984@sha256:ecad6c96a5a8f94613cb310c644dc536b40866aeaefce2229c92e221fd4960ce into the portainer WebUI but seems like that link 404's?

**Comment by jakoch** [comment]
Hmm.. strange, works for me.

I tested that URL on the Windows CLI:
![image](https://github.com/jakoch/jupyter-devbox/assets/85608/28613585-7ac7-4bb1-9348-986e11be0811)
Which means that pulling the individual (per architecture) images works.

Here i'm pulling the arm64 image directly:
![image](https://github.com/jakoch/jupyter-devbox/assets/85608/735ae85f-ec1d-4307-9688-e0cc96ee4b3f)

But, the way this is supposed to work, is to fetch the main image tag  `FROM ghcr.io/jakoch/jupyter-devbox:latest`,
which is then automatically resolved into the matching architecture image via the manifest.

- `FROM ghcr.io/jakoch/jupyter-devbox:sha-25824be`:
![image](https://github.com/jakoch/jupyter-devbox/assets/85608/f3a7c3a4-b08f-4200-ae72-df80fd56b097)
- and `sha-25824be` is currently also tagged as latest = `FROM ghcr.io/jakoch/jupyter-devbox:latest`:
![image](https://github.com/jakoch/jupyter-devbox/assets/85608/354e0caa-e827-4554-af1d-ea68367366d7)

**Comment by samuk** [comment]
I can get it down now, but running it exits with: "No log line matching the '' filter"

Maybe I should try that RPI config as I am running it on a Pi.

**Comment by jakoch** [comment]
can you check `docker logs` of the container?

**Comment by samuk** [comment]
The logs provide the text above` "No log line matching the '' filter"` I may just be deploying it incorrectly. I'll check the config and have another go sometime.

**Comment by jakoch** [comment]
Closing as done. Container is build for linux/amd64 and linux/arm64.
